const foodProducts = [
    { id: 1, name: "Pepperoni Pizza", image: "https://via.placeholder.com/150" },
    { id: 2, name: "Cheeseburger", image: "https://via.placeholder.com/150" },
    { id: 3, name: "Spaghetti Bolognese", image: "https://via.placeholder.com/150" },
    { id: 4, name: "Chicken Sandwich", image: "https://via.placeholder.com/150" },
    { id: 5, name: "Tuna Salad", image: "https://via.placeholder.com/150" },
    { id: 6, name: "French Fries", image: "https://via.placeholder.com/150" },
    { id: 7, name: "Sushi Roll", image: "https://via.placeholder.com/150" },
    { id: 8, name: "Chocolate Cake", image: "https://via.placeholder.com/150" },
    { id: 9, name: "Apple Pie", image: "https://via.placeholder.com/150" },
    { id: 10, name: "Grilled Cheese", image: "https://via.placeholder.com/150" },
    { id: 11, name: "Caesar Salad", image: "https://via.placeholder.com/150" },
    { id: 12, name: "Pancakes", image: "https://via.placeholder.com/150" },
    { id: 13, name: "Fish Tacos", image: "https://via.placeholder.com/150" },
    { id: 14, name: "Beef Burrito", image: "https://via.placeholder.com/150" },
    { id: 15, name: "Margarita Pizza", image: "https://via.placeholder.com/150" },
    { id: 16, name: "Avocado Toast", image: "https://via.placeholder.com/150" },
    { id: 17, name: "Mac and Cheese", image: "https://via.placeholder.com/150" },
    { id: 18, name: "Vegetable Stir Fry", image: "https://via.placeholder.com/150" },
    { id: 19, name: "BBQ Ribs", image: "https://via.placeholder.com/150" },
    { id: 20, name: "Vanilla Ice Cream", image: "https://via.placeholder.com/150" },
    { id: 21, name: "Strawberry Shortcake", image: "https://via.placeholder.com/150" },
    { id: 22, name: "Turkey Club Sandwich", image: "https://via.placeholder.com/150" },
    { id: 23, name: "Mango Smoothie", image: "https://via.placeholder.com/150" },
    { id: 24, name: "Veggie Burger", image: "https://via.placeholder.com/150" },
    { id: 25, name: "Chicken Caesar Wrap", image: "https://via.placeholder.com/150" },
    { id: 26, name: "Pulled Pork Sandwich", image: "https://via.placeholder.com/150" },
    { id: 27, name: "Lobster Bisque", image: "https://via.placeholder.com/150" },
    { id: 28, name: "Shrimp Cocktail", image: "https://via.placeholder.com/150" },
    { id: 29, name: "Chocolate Chip Cookies", image: "https://via.placeholder.com/150" },
    { id: 30, name: "Chicken Alfredo", image: "https://via.placeholder.com/150" },
    { id: 31, name: "Beef Stroganoff", image: "https://via.placeholder.com/150" },
    { id: 32, name: "Greek Salad", image: "https://via.placeholder.com/150" },
    { id: 33, name: "Fettuccine Carbonara", image: "https://via.placeholder.com/150" },
    { id: 34, name: "Minestrone Soup", image: "https://via.placeholder.com/150" },
    { id: 35, name: "Roast Chicken", image: "https://via.placeholder.com/150" },
    { id: 36, name: "Stuffed Bell Peppers", image: "https://via.placeholder.com/150" },
    { id: 37, name: "Cinnamon Rolls", image: "https://via.placeholder.com/150" },
    { id: 38, name: "Eggplant Parmesan", image: "https://via.placeholder.com/150" },
    { id: 39, name: "Quiche Lorraine", image: "https://via.placeholder.com/150" },
    { id: 40, name: "Lemon Meringue Pie", image: "https://via.placeholder.com/150" },
    { id: 41, name: "Buffalo Wings", image: "https://via.placeholder.com/150" },
    { id: 42, name: "Clam Chowder", image: "https://via.placeholder.com/150" },
    { id: 43, name: "Carrot Cake", image: "https://via.placeholder.com/150" },
    { id: 44, name: "BLT Sandwich", image: "https://via.placeholder.com/150" },
    { id: 45, name: "Chicken Tikka Masala", image: "https://via.placeholder.com/150" },
    { id: 46, name: "Vegetable Curry", image: "https://via.placeholder.com/150" },
    { id: 47, name: "Fish and Chips", image: "https://via.placeholder.com/150" },
    { id: 48, name: "Pad Thai", image: "https://via.placeholder.com/150" },
    { id: 49, name: "Chili Con Carne", image: "https://via.placeholder.com/150" },
    { id: 50, name: "Cobb Salad", image: "https://via.placeholder.com/150" },
    { id: 200, name: "BBQ Pulled Pork Pizza", image: "https://via.placeholder.com/150" }
];

export default foodProducts;
